export const DEVICES: string[] = [
  "Samsung Galaxy S24 (Android 15)",
  "Google Pixel 8 (Android 14)",
  "Samsung Galaxy Z Fold6 (Android 15)",
  "OnePlus 12 (Android 14)",
  "Google Pixel 9 (Android 15)",
  "Samsung Galaxy S23 Ultra (Android 14)",
  "Xiaomi 14 Pro (Android 14)",
  "Motorola Edge 50 Ultra (Android 14)",
  "Sony Xperia 1 VI (Android 14)",
  "Google Pixel Fold 2 (Android 15)",
  "Asus ROG Phone 8 (Android 14)",
  "Samsung Galaxy A55 (Android 14)",
  "Nothing Phone (2) (Android 14)",
  "Google Pixel 7a (Android 14)",
  "Moto G Stylus (API 30)",
  "Samsung Galaxy Tab S9 (Android 14)",
  "Oppo Find X7 Ultra (Android 14)",
  "Vivo X100 Pro (Android 14)",
  "Honor Magic6 Pro (Android 14)",
  "Google Pixel 6 (Android 13)",
];
